# Generated by Django 5.0.3 on 2024-03-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('costs', models.IntegerField()),
            ],
        ),
    ]
